### ISSUE TITLE
Error 404 on upload 

### ISSUE THREAD

**Issue by ades4827** [frugan-dev/acf-uppy#3]
Hi, 
I have a problem uploading a file using a permalink rule different from: "Post Name".
When i use a permalink with custom structure like "/blog/%category%/%postname%/" the upload return a http 404 Error on wp-tus upload call.

Many thanks

**Comment by frugan-dev** [comment]
Hi @ades4827,

i recommend that you first of all flush the WP permalinks, to make sure these rewriting rules https://github.com/frugan-it/acf-uppy/blob/master/src/AcfUppy.php#L116 have been detected.

Then check what the url is giving you a 404 error, and possibly try to modify it appropriately (adding "/blog" if not present) using these 2 hooks:

```
apply_filters( 'acf_uppy/base_path', $basePath );
apply_filters( 'acf_uppy/api_path', $apiPath );
```
I hope I was helpful, otherwise please feel free to reply!
And if you like this project, consider leaving a star to make it more popular, thanks!
